/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TranslitPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var TRANSLIT_MAP = {
  // 4-character combinations
  "shch": "\u0449",
  "SHCH": "\u0429",
  "Shch": "\u0429",
  // 2-character combinations
  "yo": "\u0451",
  "zh": "\u0436",
  "ts": "\u0446",
  "ch": "\u0447",
  "sh": "\u0448",
  "ju": "\u044E",
  "ya": "\u044F",
  "je": "\u044D",
  "''": "\u044A",
  "Yo": "\u0401",
  "Zh": "\u0416",
  "Ts": "\u0426",
  "Ch": "\u0427",
  "Sh": "\u0428",
  "Yu": "\u042E",
  "Ya": "\u042F",
  "Je": "\u042D",
  "YO": "\u0401",
  "ZH": "\u0416",
  "TS": "\u0426",
  "CH": "\u0427",
  "SH": "\u0428",
  "YU": "\u042E",
  "YA": "\u042F",
  "JE": "\u042D",
  // Single characters
  "a": "\u0430",
  "b": "\u0431",
  "v": "\u0432",
  "g": "\u0433",
  "d": "\u0434",
  "e": "\u0435",
  "z": "\u0437",
  "i": "\u0438",
  "j": "\u0439",
  "y": "\u044B",
  "k": "\u043A",
  "l": "\u043B",
  "m": "\u043C",
  "n": "\u043D",
  "o": "\u043E",
  "p": "\u043F",
  "r": "\u0440",
  "s": "\u0441",
  "t": "\u0442",
  "u": "\u0443",
  "f": "\u0444",
  "h": "\u0445",
  "c": "\u0446",
  "'": "\u044C",
  "A": "\u0410",
  "B": "\u0411",
  "V": "\u0412",
  "G": "\u0413",
  "D": "\u0414",
  "E": "\u0415",
  "Z": "\u0417",
  "I": "\u0418",
  "J": "\u0419",
  "Y": "\u042B",
  "K": "\u041A",
  "L": "\u041B",
  "M": "\u041C",
  "N": "\u041D",
  "O": "\u041E",
  "P": "\u041F",
  "R": "\u0420",
  "S": "\u0421",
  "T": "\u0422",
  "U": "\u0423",
  "F": "\u0424",
  "H": "\u0425",
  "C": "\u0426"
};
var TRANSLIT_KEYS = Object.keys(TRANSLIT_MAP).sort((a, b) => b.length - a.length);
var TranslitPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.translitMode = false;
  }
  async onload() {
    console.log("Loading Translit Plugin");
    this.addTranslitStyles();
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar();
    this.addCommand({
      id: "toggle-translit",
      name: "Toggle Translit Mode",
      hotkeys: [{ modifiers: [], key: "F2" }],
      callback: () => {
        this.toggleTranslitMode();
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        if (this.translitMode) {
          this.handleEditorChange(editor);
        }
      })
    );
  }
  onunload() {
    console.log("Unloading Translit Plugin");
    if (this.styleEl) {
      this.styleEl.remove();
    }
  }
  addTranslitStyles() {
    this.styleEl = document.createElement("style");
    this.styleEl.id = "translit-plugin-styles";
    this.styleEl.textContent = `
			/* Blue dotted border around the entire editor */
			.translit-mode-active.cm-editor,
			.translit-mode-active .cm-editor,
			.translit-mode-active.cm-scroller,
			.translit-mode-active .cm-scroller {
				border: 1px dotted #4a9eff !important;
				border-radius: 4px !important;
				box-sizing: border-box !important;
			}
			
			/* Alternative: add border to the editor container */
			.markdown-source-view.translit-mode-active .cm-editor {
				border: 1px dotted #4a9eff !important;
				border-radius: 4px !important;
			}
		`;
    document.head.appendChild(this.styleEl);
  }
  toggleTranslitMode() {
    this.translitMode = !this.translitMode;
    this.updateStatusBar();
    this.updateEditorHighlight();
    new import_obsidian.Notice(this.translitMode ? "Translit Mode: ON" : "Translit Mode: OFF");
  }
  updateStatusBar() {
    if (this.translitMode) {
      this.statusBarItem.setText("\u{1F1F7}\u{1F1FA} TRANSLIT");
      this.statusBarItem.style.backgroundColor = "#4a9eff";
      this.statusBarItem.style.color = "white";
      this.statusBarItem.style.padding = "2px 8px";
      this.statusBarItem.style.borderRadius = "3px";
    } else {
      this.statusBarItem.setText("");
      this.statusBarItem.style.backgroundColor = "";
      this.statusBarItem.style.color = "";
      this.statusBarItem.style.padding = "";
    }
  }
  updateEditorHighlight() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const cmEditor = activeView.editor.cm;
    if (cmEditor && cmEditor.dom) {
      if (this.translitMode) {
        cmEditor.dom.classList.add("translit-mode-active");
        const sourceView = cmEditor.dom.closest(".markdown-source-view");
        if (sourceView) {
          sourceView.classList.add("translit-mode-active");
        }
      } else {
        cmEditor.dom.classList.remove("translit-mode-active");
        const sourceView = cmEditor.dom.closest(".markdown-source-view");
        if (sourceView) {
          sourceView.classList.remove("translit-mode-active");
        }
      }
    }
  }
  handleEditorChange(editor) {
    if (!this.translitMode)
      return;
    const cursor = editor.getCursor();
    const line = cursor.line;
    const cursorPos = cursor.ch;
    if (cursorPos === 0)
      return;
    const lineText = editor.getLine(line);
    const pos = cursorPos - 1;
    const chr = lineText.charAt(pos);
    let offset = 0;
    let cyr = "";
    if (pos > 0) {
      const prevChr = lineText.charAt(pos - 1);
      let prevLat = "";
      for (const [latin, cyrillic] of Object.entries(TRANSLIT_MAP)) {
        if (cyrillic === prevChr && latin.length === 1) {
          prevLat = latin;
          break;
        }
      }
      if (prevLat) {
        const combo = prevLat + chr;
        if (TRANSLIT_MAP[combo]) {
          cyr = TRANSLIT_MAP[combo];
          offset = 1;
        }
      }
    }
    if (!cyr) {
      cyr = TRANSLIT_MAP[chr];
    }
    if (cyr) {
      const from = { line, ch: pos - offset };
      const to = { line, ch: pos + 1 };
      editor.replaceRange(cyr, from, to);
    }
  }
};
